import type {
  CreateDatabaseParameters
} from "@notionhq/client/build/src/api-endpoints";
import {
  titleProperty,
  relationProperty,
  richTextProperty,
  selectProperty,
  numberProperty,
  dateProperty,
  checkboxProperty,
  emailProperty,
  phoneProperty,
  urlProperty,
  createAddressFields,
  createMetadataFields,
  statusOptions,
  collectionMethodOptions,
  taxExemptOptions
} from "./utils";

export const getInvoiceSchema = (
  customerDatabaseId: string,
  chargeDatabaseId: string,
  paymentIntentDatabaseId: string
): CreateDatabaseParameters["properties"] => {
  const properties: CreateDatabaseParameters["properties"] = {
  "Invoice ID": titleProperty(),
  "Link": urlProperty(),
  "Customer": relationProperty(customerDatabaseId),
  "Invoice Number": richTextProperty(),
  "Status": selectProperty(statusOptions.invoice),
  "Collection Method": selectProperty(collectionMethodOptions),
  "Currency": richTextProperty(),
  "Total": numberProperty(),
  "Subtotal": numberProperty(),
  "Amount Due": numberProperty(),
  "Amount Paid": numberProperty(),
  "Amount Remaining": numberProperty(),
  "Amount Overpaid": numberProperty(),
  "Amount Shipping": numberProperty(),
  "Starting Balance": numberProperty(),
  "Ending Balance": numberProperty(),
  "Created Date": dateProperty(),
  "Due Date": dateProperty(),
  "Period Start": dateProperty(),
  "Period End": dateProperty(),
  "Finalized At": dateProperty(),
  "Paid At": dateProperty(),
  "Voided At": dateProperty(),
  "Next Payment Attempt": dateProperty(),
  "Billing Reason": selectProperty([
    {name: "manual", color: "gray" as const},
    {name: "subscription", color: "blue" as const},
    {name: "subscription_create", color: "blue" as const},
    {name: "subscription_cycle", color: "blue" as const},
    {name: "subscription_threshold", color: "orange" as const},
    {name: "subscription_update", color: "purple" as const},
    {name: "upcoming", color: "yellow" as const},
    {name: "automatic_pending_invoice_item_invoice", color: "purple" as const},
    {name: "quote_accept", color: "green" as const}
  ]),
  "Attempted": checkboxProperty(),
  "Attempt Count": numberProperty(),
  "Auto Advance": checkboxProperty(),
  "Live Mode": checkboxProperty(),
  "Customer Name": richTextProperty(),
  "Customer Email": emailProperty(),
  "Customer Phone": phoneProperty(),
  "Customer Tax Exempt": selectProperty(taxExemptOptions),
  ...createAddressFields("Customer"),
  "Customer Shipping Name": richTextProperty(),
  "Customer Shipping Phone": phoneProperty(),
  ...createAddressFields("Customer Shipping"),
  "Automatic Tax Enabled": checkboxProperty(),
  "Automatic Tax Status": selectProperty([
    {name: "complete", color: "green" as const},
    {name: "failed", color: "red" as const},
    {name: "requires_location_inputs", color: "yellow" as const}
  ]),
  "Automatic Tax Disabled Reason": selectProperty([
    {name: "finalization_requires_location_inputs", color: "yellow" as const},
    {name: "finalization_system_error", color: "red" as const}
  ]),
  "Automatic Tax Provider": richTextProperty(),
  "Automatically Finalizes At": dateProperty(),
  "Effective At": dateProperty(),
  "Description": richTextProperty(),
  "Footer": richTextProperty(),
  "Statement Descriptor": richTextProperty(),
  "Default Payment Method": richTextProperty(),
  "Default Source": richTextProperty(),
  "Hosted Invoice URL": urlProperty(),
  "Invoice PDF URL": urlProperty(),
  "Receipt Number": richTextProperty(),
  "Account Country": richTextProperty(),
  "Account Name": richTextProperty(),
  "Application": richTextProperty(),
  "On Behalf Of": richTextProperty(),
  "Latest Revision": richTextProperty(),
  "From Invoice Action": richTextProperty(),
  "From Invoice ID": richTextProperty(),
  "Parent Type": selectProperty([
    {name: "subscription_details", color: "blue" as const},
    {name: "quote_details", color: "green" as const}
  ]),
  "Line Items Count": numberProperty(),
  "Payments Count": numberProperty(),
  "Webhooks Delivered At": dateProperty(),
  "Test Clock": richTextProperty(),
  "Default Tax Rates Count": numberProperty(),
  "Default Tax Rates": richTextProperty(),
  "Discounts Count": numberProperty(),
  "Discounts": richTextProperty(),
  "Custom Fields Count": numberProperty(),
  "Custom Fields": richTextProperty(),
  "Customer Tax IDs Count": numberProperty(),
  "Customer Tax IDs": richTextProperty(),
  "Account Tax IDs Count": numberProperty(),
  "Account Tax IDs": richTextProperty(),
  "Total Discount Amounts Count": numberProperty(),
  "Total Discount Amounts": numberProperty(),
  "Total Pretax Credit Amounts Count": numberProperty(),
  "Total Pretax Credit Amounts": numberProperty(),
  "Total Taxes Count": numberProperty(),
  "Total Taxes": richTextProperty(),
  "Subtotal Excluding Tax": numberProperty(),
  "Total Excluding Tax": numberProperty(),
  "Pre Payment Credit Notes Amount": numberProperty(),
  "Post Payment Credit Notes Amount": numberProperty(),
  "Shipping Cost Amount Subtotal": numberProperty(),
  "Shipping Cost Amount Tax": numberProperty(),
  "Shipping Cost Amount Total": numberProperty(),
  "Shipping Cost Shipping Rate": richTextProperty(),
  "Shipping Details Name": richTextProperty(),
  "Shipping Details Phone": phoneProperty(),
  ...createAddressFields("Shipping Details"),
  "Threshold Reason Amount GTE": numberProperty(),
  "Threshold Reason Item Reasons Count": numberProperty(),
  "Issuer Type": selectProperty([
    {name: "self", color: "blue" as const},
    {name: "account", color: "green" as const}
  ]),
  "Issuer Account": richTextProperty(),
  "Confirmation Secret Type": richTextProperty(),
  "Confirmation Secret Client Secret": richTextProperty(),
  "Last Finalization Error Type": richTextProperty(),
  "Last Finalization Error Code": richTextProperty(),
  "Last Finalization Error Message": richTextProperty(),
  "Payment Method Types Count": numberProperty(),
  "Payment Method Types": richTextProperty(),
  "Primary Charge": relationProperty(chargeDatabaseId),
  "Primary Payment Intent": relationProperty(paymentIntentDatabaseId),
  ...createMetadataFields()
  };

  return properties;
}